taskleaf/config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'sessions/new'
  namespace :admin do
    resources :users
  end
    root to: 'tasks#index'
    resources :tasks do
      post :confirm, action: :confirm_new, on: :new
      post :import, on: :collection
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

taskleaf/app/models/task.rb
class Task < ApplicationRecord
    has_one_attached :image
    validates :name, presence: true
    validates :name, length: {maximum: 30}
    validate :validate_name_not_including_comma

    belongs_to :user

    scope :recent, -> { order(created_at: :desc)}

    def self.ransackable_attributes(auth_object = nil)
      %w[name created_at]
    end

    def self.ransackable_associations(auth_object = nil)
      []
    end

    def self.csv_attributes
      # CSVにどの属性をどの順番で出力するかをcsv_attributeというクラスメソッドから得られるように定義する
      ["name", "description", "created_at", "updated_at"]
    end

    def self.generate_csv
      # CSV.generateを使ってCSVデータの文字列を生成する
      CSV.generate(headers: true) do |csv|
        # 変数csvにクラスメソッドcsv_attributesで定義した配列を格納する(<<... 配列に中身を追加)
        # CSVの1行目としてヘッダを出力する
        csv << csv_attributes
        all.each do |task|
          # allメソッドで全タスクを取得し、1レコード毎にCSVの1行を出力する
          csv << csv_attributes.map{|attr| task.send(attr)}
        end
      end
    end

    # fileという名前の引数でアップロードされたファイルの内容にアクセスするためのオブジェクトを受け取る
    def self.import(file)
      # CSV.foreachを使って、CSVファイルを1行ずつ読み込む
      CSV.foreach(file.path, headers: true) do |row|
        # CSV1行ごとに、Taskインスタンスを生成する(newはTask.newと同意)
        task = new
        # 生成したTaskインスタンスの各属性に、CSVの1行の属性を加工して入れ込む
        task.attributes = row.to_hash.slice(*csv_attributes)
        # Taskインスタンスをデータベースに登録する
        task.save!
      end
    end

    private

    def validate_name_not_including_comma
      errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
    end
end

taskleaf/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :tasks
end

taskleaf/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :require_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.name}」を更新しました"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_path unless current_user.admin
  end
end

taskleaf/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

taskleaf/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

taskleaf/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])

    respond_to do |format|
      # HTMLフォーマットについては特に処理を指定しない(index.html.slimを表示する)
      format.html
      # send_dataメソッドを使ってレスポンスを送り出し、送り出したデータを部サウザからファイルとしてダウンロードできるようにする
      format.csv{send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%dS')}.csv"}
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{task.name}」を更新しました。"
  end

  def create
    @task = current_user.tasks.new(task_params)

    # 「戻る」ボタンが押された場合は、現在のタスクの内容を引き継いだ状態で新規登録のフォーム画面を表示する
    if params[:back].present?
      # 新規登録フォームの画面を表示する処理はここで定義している
      render :new
      return
    end

    if @task.save
      SampleJob.perform_later
      logger.debug "task: #{@task.attributes.inspect}"
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    head :no_content
  end

  def confirm_new
    # 新規登録画面から受け取ったパラメータをもとにタスクイブジェクトを作成して、@taskに代入
    @task = current_user.tasks.new(task_params)
    # 問題があれば検証エラーメッセージとともに出力する
    render :new unless @task.valid?
  end

  def import
    # 画面上のフィールドからアップロードされたファイルオブジェクトを引数に、関連越しに先程実装したimportメソッドを呼び出している
    current_user.tasks.import(params[:file])
    #インポートが終わった後にタスク一覧画面に遷移する
    redirect_to tasks_url, notice: "タスクを追加した"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :image)
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

taskleaf/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

taskleaf/app/helpers/sessions_helper.rb
module SessionsHelper
end

taskleaf/app/helpers/tasks_helper.rb
module TasksHelper
end

taskleaf/app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li = message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      =f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

taskleaf/app/views/admin/users/edit.html.slim
h1 Admin::Users#edit
p Find me in app/views/admin/users/edit.html.slim

h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: {user: @user}

= link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか?"}, class: 'btn btn-danger'

taskleaf/app/views/admin/users/index.html.slim
h1 Admin::Users#index
p Find me in app/views/admin/users/index.html.slim

h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか?"}, class: 'btn btn-danger'

taskleaf/app/views/admin/users/new.html.slim
h1 Admin::Users#new
p Find me in app/views/admin/users/new.html.slim

h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user}

taskleaf/app/views/admin/users/show.html.slim
h1 Admin::Users#show
p Find me in app/views/admin/users/show.html.slim

h1 ユーザーの詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

taskleaf/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'タスク一覧', tasks_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to ' ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to ' ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
      .alert.alert-succes= flash.notice
    = yield

taskleaf/app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

taskleaf/app/views/tasks/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th= Task.human_attribute_name(:name)
        td= @task.name
        = f.hidden_field :name
      tr
        th= Task.human_attribute_name(:description)
        td= simple_format(@task.description)
        = f.hidden_field :description
  =f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'
  =f.submit '登録', class: 'btn btn-primary'

taskleaf/app/views/tasks/edit.html.slim
h1 Tasks#edit
p Find me in app/views/tasks/edit.html.slim

h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}

taskleaf/app/views/tasks/index.html.slim
h1 Tasks#index
p Find me in app/views/tasks/index.html.slim

h1 タスク一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'
= link_to '新規登録', new_task_path, class: 'btn btn-primary'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks
table.table.table-hover
  thread.thread-default
    tr
      th= sort_link(@q, :name)
      th= Task.human_attribute_name(:created_at)
      th
  tbody
    - @tasks.each do |task|
      tr
        td= link_to task.name, task
        td= task.created_at
        td
          = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
          = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか?"}, class: 'btn btn-danger'

= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file
  = submit_tag "インポート", class: 'btn btn-primary'

taskleaf/app/views/tasks/new.html.slim
h1 Tasks#new
p Find me in app/views/tasks/new.html.slim

h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}

taskleaf/app/views/tasks/show.html.slim
h1 Tasks#show
p Find me in app/views/tasks/show.html.slim

h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Task.human_attribute_name(:image)
      td= image_tag @task.image if @task.image.attached?
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at
= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: {confirm: "タスク「#{@task.name}」を削除します。よろしいですか?"}, class: 'btn btn-danger'